sqlite> SELECT first_name, last_name
   ...> FROM persons
   ...> WHERE age <= 29
   ...> ORDER BY last_name;
+------------+----------------+
| first_name |   last_name    |
+------------+----------------+
| Paddy      | Abrehart       |
| Alina      | Adanez         |
| Bax        | Aldrin         |
| Ivett      | Aristide       |
| Waylin     | Assel          |
| Hayward    | Autrie         |
| Howey      | Bantock        |
| Shandra    | Beadon         |
| Linea      | Beesey         |
| Konstantin | Birds          |
| Ariella    | Birt           |
| Husain     | Booth          |
| Meir       | Brake          |
| Ian        | Bretherick     |
| Renee      | Brobyn         |
| Linn       | Brodley        |
| Philippa   | Canfield       |
| Denis      | Caplen         |
| Sorcha     | Casewell       |
| Royal      | Cass           |
| Deny       | Chattock       |
| Jeffry     | Christopherson |
| Larina     | Coate          |
| Tally      | Cobbald        |
| Aretha     | Cosgrive       |
| Wolfy      | Courson        |
| Maurise    | Crick          |
| Zulema     | Cringle        |
| Judith     | Crucetti       |
| Robinet    | Culross        |
| Byrann     | Darmody        |
| Mateo      | Davioud        |
| Tymothy    | Demetr         |
| Livvie     | Dible          |
| Jill       | Domenico       |
| Berne      | Dougal         |
| Olvan      | Ducker         |
| Eward      | Eason          |
| Osborne    | Easson         |
| Emmery     | Edgeley        |
| Chelsy     | Everex         |
| Irving     | Feveryear      |
| Sarine     | Ghion          |
| Marylinda  | Girdlestone    |
| Paddie     | Goucher        |
| Raf        | Gowrich        |
| Katlin     | Griffey        |
| Cinderella | Guilder        |
| Isador     | Guitton        |
| Virgilio   | Guly           |
| Mariquilla | Gwyllt         |
| Karina     | Habert         |
| Margareta  | Hammerstone    |
| Barbi      | Haston         |
| Kizzie     | Hawkin         |
| Law        | Hurt           |
| Elga       | Iacovielli     |
| Tabor      | Illesley       |
| Irvin      | Ilyenko        |
| Grenville  | Instone        |
| Silvain    | Jinkin         |
| Flori      | Jirasek        |
| Filbert    | Josovitz       |
| Hank       | Keenan         |
| Cristina   | King           |
| Markus     | Klesel         |
| Denis      | Knight         |
| Ania       | Knottley       |
| Cornie     | Knowlton       |
| Mohandas   | Lage           |
| Richmond   | Laste          |
| Tatiana    | Leaf           |
| Wittie     | Lemon          |
| Emmalynn   | Leven          |
| Carlos     | Lupton         |
| Pierette   | Lyston         |
| Basia      | Lytlle         |
| Eric       | M'cowis        |
| Vicky      | Matitiaho      |
| Fayre      | Mayte          |
| Calv       | Naerup         |
| Carena     | Nibley         |
| Corbet     | Niess          |
| Noella     | O'Hickee       |
| Inglis     | Pedron         |
| Beverlee   | Phare          |
| Mildrid    | Podd           |
| Oswald     | Rathbourne     |
| Alvis      | Ratledge       |
| Goober     | Reding         |
| Zach       | Renner         |
| Walsh      | Ricarde        |
| Anthe      | Ritter         |
| Tamarah    | Rockhill       |
| Oswell     | Ruckert        |
| Jabez      | Servante       |
| Justino    | Shearmur       |
| Eveline    | Skeermor       |
| Pattie     | Skoyles        |
| Lambert    | Snelle         |
| Thedric    | Stagge         |
| Sasha      | Stickley       |
| Eal        | Swoffer        |
| Ilyse      | Symper         |
| Juliann    | Taft           |
| Jason      | Teanby         |
| Babbette   | Timberlake     |
| Kerstin    | Tolefree       |
| Jennica    | Totman         |
| Zared      | Towers         |
| Rubin      | Treppas        |
| Sheffield  | Tullis         |
| Krissy     | Urrey          |
| Krystle    | Varah          |
| Avrom      | Veeler         |
| Demetria   | Venner         |
| Julienne   | Wearne         |
| Frankie    | Wewell         |
| Gabi       | Wilber         |
| Huey       | Worner         |
+------------+----------------+
sqlite> 
